name: Build BusEye APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Recreate Android Project & Sync Code
        run: |
          mkdir temp_app
          cd temp_app
          flutter create --org com.buseye.app --project-name buseye_app .
          cp -f ../pubspec.yaml ./pubspec.yaml
          cp -rf ../lib ./
          flutter pub get
          flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: temp_app/build/app/outputs/flutter-apk/app-release.apk
